name: Lint, generate code and run tests
on:
  push:
    branches:
      - master

env:
  GO_VERSION: 1.16.5
  BUF_VERSION: 0.43.2
  TOKEN: ${{ github.token }}

jobs:
  proto-breaking:
    name: Run proto breaking check
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'ref/head/master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: bufbuild/buf-setup-action@v0.1.0
        with:
          version: ${{ env.BUF_VERSION }}
      - name: Install protobuf requirements 
        run: | 
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
          go install github.com/envoyproxy/protoc-gen-validate@v0.6.1
      - name: Checking protobufs for breaking changes
        uses: bufbuild/buf-breaking-action@v0.2.0
        with:
          against: 'https://github.com/aranw/buf-build-action-test.git#branch=master,ref=HEAD~1'
          github_token: ${{ env.TOKEN }} 
