on:
  workflow_dispatch:

jobs:
  lint-build:
    name: buf check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aranw/build-buf-action@feature/envoy-validate
        with:
          bufVersion: v0.31.1
          protocPlugins:
            go@v1.25.0 go-grpc@v1.0.1 python_betterproto@2.0.0b2 ts-proto@1.39.0
            grpc-java@1.34.0 envoy-gen-validate@v0.6.1
          bufArgs:
            generate --config buf.yaml --template buf.gen.yaml
